### ISSUE TITLE
Doesn't work with LSPosed in zygisk mode

### ISSUE THREAD

**Issue by 0xphk** [philipp1993/NFCExtendedLengthFix#2]
Using Android 9 on MotoX4 with Magisk 25.2+zygisk and LSPosed 1.8.4 module.
LSPosed claims that XPosed modules should be compatible.

Module installs fine from Playstore and apk and is listed and activated in LSPosed Manager.
But Ausweisapp2 tells that id card is removed during reading and/or crashes.

And it looks like ```com.android.nfc``` crashes as well sometimes. 

I can supply logged stuff with logcat if that helps. Any idea?

**Comment by philipp1993** [comment]
Not all NFC chips are capable of extended length. This module was needed on older Android Versions, as extended length was never supported in software, besides being supported on some hardware platforms. 
The software problem is fixed in newer upstream Android Versions. Now there are only hardware limitations left.
This module will not be updated.
